name: 'github-actions-merger'
description: 'Merge pull-requests with metadata'
author: 'abema'
branding:
  icon: 'git-merge'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://abema/github-actions-merger@sha256:2fd78dac7f26b81a128e73107a6342356f27aca95477c6d1dba167483febd09b'
inputs:
  merge_method:
    description: 'merge method'
    required: false
    default: 'merge'
  github_token:
    description: 'github token'
    required: true
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repository'
    required: true
  pr_number:
    description: 'pull request number'
    required: true
  comment:
    description: 'pull comment'
    required: true
  mergers:
    description: 'github username who can trigger merger. every user is allowed if not specified. format must be comma separated .e.g. na-ga,0daryo'
    required: false
  enable_auto_merge:
    description: 'enable auto merge'
    required: false
  git_trailers:
    description: 'git trailers'
    required: false
