name: 'github-actions-merger'
description: 'merge pull request with labels'
author: 'abema'
branding:
  icon: 'meh'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  merge_method:
    description: 'merge method'
    required: false
    default: 'merge'
  github_token:
    description: 'github token'
    required: true
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repository'
    required: true
  pr_number:
    description: 'pull request number'
    required: true
  comment:
    description: 'pull comment'
    required: true
  mergers:
    description: 'github username who can trigger merger. every user is allowed if not specified. format must be comma separated .e.g. na-ga,0daryo'
    required: false
  auto_approvers:
    description: 'github username who can trigger automatic approve in the event of an unable to merge condition. every user is do nothing if not specified. format must be comma separated .e.g. na-ga,0daryo'
    required: false
